server:
  port: 8981
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
            
  main:
    web-application-type: reactive
    
    
#okta authentication OPEN

okta:
  oauth2:
    issuer: https://dev-69203606.okta.com/oauth2/default
    audience: api://default
    client-id: 0oabd5lttejvOufm25d7
    client-secret: hcSbbFmvbMS6-zc8ltj5wL_0NSMu2qE6rNP1Su7_mYDpL4AmvVEdhAIBR5ijwNZ1
    scopes: openid, profile, email, offline_access

#okta authentication END
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8980/eureka